#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Elegant Scipy
author                      : Juan Nunez-Iglesias, Stéfan van der Walt, Harriet Dashnow
copyright                   : "2021"
logo                        : _images/cover.jpg

only_build_toc_files: true

parse:
  myst_extended_syntax: true

execute:
  execute_notebooks: cache

latex:
  latex_engine: xelatex
  latex_documents:
    targetname: elegant-scipy.tex

sphinx:
  config:
    latex_logo: _images/cover.jpg
