# Book settings
title: Elegant Scipy
author: Juan Nunez-Iglesias (@jni), Harriet Dashnow (@hdashnow), and Stéfan van der Walt (@stefanv)
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex
